splendidinternet/Magento2_German_LocalePack_de_DE

composer.json
Hi, I want to make this available on packagist, but in order to do so I had to fix the composer.json file.
=> Composer fix

de_DE.csv
Steuertzonen -> Steuerzonen
Ihe Bestellung -> Ihre Bestellung
=> Rechtschreibkorrekturen

de_DE.csv
=> Fix HTML Tag type

de_DE.csv
Korrekturen: https://github.com/splendidinternet/Magento2_German_LocalePack_de_DE/issues/12
Ergänzungen: https://github.com/splendidinternet/Magento2_German_LocalePack_de_DE/issues/13
=> Weitere Korrekturen nach Issue #12 und Issue #13

de_DE.csv
fixes splendidinternet/Magento2_German_LocalePack_de_DE#19
=> CHANGE fix some line of translation

de_DE.csv
=> Diverse Korrekturen

de_DE.csv
The eagle eye of our tester has spotted a crazy grammatical mistake - a missing comma in a phrase. This patch adds the comma.
=> Issue #32: Adding a missing comma to the translation phrase.

de_DE.csv
Minify JavaScript Files,JavaScript-Dateien verkürzen
=> Fixed Tyop

de_DE.csv
Made translatable in https://github.com/magento/magento2/commit/1430015ba80f6518ea93abb55079521ed7e8e5e5
=> Translate e-mail subjects

de_DE.csv
placeholders are wrong!
%1% 2% 3 -> %1 %2 %3
=> Fix error on saving cart price rule

de_DE.csv
German translations for
* `Change Email`
* `Forgot Your Password`
* `It's a default billing address.`
* `It's a default shipping address.`
* `Reset My Password`
* `You have no credit cards.`
=> Translate customer address related strings

de_DE.csv
You already have an account with us. Sign in or continue as guest.
-> Sie haben bereits ein Konto bei uns. Melden Sie sich an oder fahren Sie als Gast fort.
=> Zeile im Checkout übersetzt

de_DE.csv
'Alle dem Warenkorb hinzufügen'
-> 'Alles in den Warenkorb'
'Zum Warenkorb hinzufügen'
-> 'In den Warenkorb'
=> Übersetzung 'In den Warenkorb'

de_DE.csv
`ui/grid/filters/elements/select,UI / Raster/ Filter / Elemente / Auswählen`` entfernt
=> Zeile entfernt, siehe Issue #61

de_DE.csv
=> Übersetzung-Layered Navigation

de_DE.csv
siehe Issue #47
state -> Zustand
status -> Status
=> Bestellstatus vs. Bestellzustand

de_DE.csv
=> Changed two translations

de_DE.csv
Fix typo in german translation for "Browser Capabilities Detection"
=> :globe_with_meridians: Fix typo

de_DE.csv
Add missing translation for "You aren't subscribed to our newsletter." and fix mess on 
```
was
was not
We archived %1 order(s).
We authorized your Return request.
Website Closed
Website code may only contain letters (a-z) numbers (0-9) or underscore (_) ' ' and the first character must be a letter."""
```
=> Add missing translation and fix messed ones

de_DE.csv
This is used in attribute management. The setting shows up if attribute is set as searchable.
=> Fix translation of search weight

de_DE.csv
see line below and [duden.de](https://www.duden.de/rechtschreibung/E_Mail_Adresse)
=> E-Mailadresse -> E-Mail-Adresse

de_DE.csv
Standard-Lieferadresse - Rechnungsadresse sollten mit dem gleichen Artikel stehen
=> Standard-Lieferadresse - Rechnungsadresse

de_DE.csv
add missing translation for "for" in 
"%1 for ""%2"".","%1 for ""%2"".",,
=> add translation text

de_DE.csv
=> [fix] removes unnecessary whitespace at product placeholder

de_DE.csv
* add missing translation, first notice with m2 2.2.6
=> :speech_balloon: add new missing translation

de_DE.csv
For example on /sales/order/history
=> Add "Einträge" (for Page, not everyting is artikel)

de_DE.csv
Charts sind Diagramme und keine Tabellen (verwendet im Admin-Dashboard)
=> chart => Diagramm

de_DE.csv
Platzhalter von 2% auf %1 korrigiert und zwei Leerzeichen entfernt.
=> Platzhalter korrigiert

de_DE.csv
Die Übersetzungen die "Treten Sie ein" für "Enter" enthalten, sind sehr seltsam.
Hier gibt es sinnvollere Übersetzungen :-)
=> :globe_with_meridians: Fix translations for 'Treten Sie ein'

de_DE.csv
=> Fix Keys with no translations

de_DE.csv
=> Fix translation errors

de_DE.csv
=> fix: wrong translation of "Concrete type"

de_DE.csv
Fixes #186 
I just replaced all those symbols by their german umlaut representation, that should fix the issue.
=> fix: replace german umlauts representation with real umlaut characters

de_DE.csv
=> change: unify translation of coupon + discount code

de_DE.csv
Fixes #191 
Also capitalizes the word "Sie" in direct speech.
=> fix: inconsistent informal language usages

de_DE.csv
Add Correct translation for Product Design Attribute not allowed
=> Fix translation for Product Design Attributes

de_DE.csv
I don't think it is possible to pay with a Visum ;)
=> Fix Visa translation
